[package]
name = "yabiir"
version = "0.1.0"
edition = "2024"
description = "Yet another bitcask implementation in rust"

[lib]
[[bin]]
name = "e"
path = "src/bin/e.rs"

[dependencies]
crc32fast = "1.5.1"
clap = { version = "4.6.6", features = ["derive"] }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "format"
harness = false