[package]
name = "yabiir"
version = "0.1.0"
edition = "2024"
description = "Yet another bitcask implementation in rust"

[dependencies]
crc32fast = "1.5.1"
clap = { version = "4.6.6", features = ["derive"] }

[lib]

[[bin]]
name = "kv"
path = "src/bin/kv.rs"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "format"
harness = false

[[bench]]
name = "keydir"
harness = false

[[bench]]
name = "datafile"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1